language: dart
sudo: false
dart:
  - stable
  - dev
before_install:
  - export CHROMEDRIVER_BINARY=/usr/bin/chromium-browser
  - export CHROMEDRIVER_ARGS=--no-sandbox
  - /usr/bin/chromium-browser --version

  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start

before_script:
# We use a slightly older version of chromedriver; the newer ones require a later
# version of chromium than is available on travis by default.
  - wget http://chromedriver.storage.googleapis.com/2.12/chromedriver_linux64.zip
  - unzip chromedriver_linux64.zip
  - sudo mv chromedriver /usr/bin/

script: ./tool/travis.sh
