language: dart
# This is necessary to use proper Chrome. Travis's version of chromium is from
# 2014.
dist: trusty
addons:
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable
  firefox: latest

dart:
  - dev

before_install:
  - export CHROMEDRIVER_BINARY=/usr/bin/google-chrome
  - export CHROMEDRIVER_ARGS=--no-sandbox
  - /usr/bin/google-chrome --version
  - firefox --version

  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start

before_script:
  - wget http://chromedriver.storage.googleapis.com/2.35/chromedriver_linux64.zip
  - unzip chromedriver_linux64.zip
  - export PATH=$PATH:$PWD
  - wget https://github.com/mozilla/geckodriver/releases/download/v0.21.0/geckodriver-v0.21.0-linux64.tar.gz
  - tar -xvzf geckodriver-v0.21.0-linux64.tar.gz
  - export PATH=$PATH:$PWD
  - ./tool/travis-setup.sh

script:
  - ./tool/travis.sh

# Only building master means that we don't run two builds for each pull request.
branches:
  only: [master]

cache:
 directories:
   - $HOME/.pub-cache
