language: dart
sudo: required
dist: trusty
addons:
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable

dart:
  - dev
  - stable

with_content_shell: true

matrix:
  allow_failures:
    - dart: dev

before_install:
  - export CHROMEDRIVER_BINARY=/usr/bin/google-chrome
  - export CHROMEDRIVER_ARGS=--no-sandbox
  - /usr/bin/chromium-browser --version

  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start

before_script:
# We use a slightly older version of chromedriver; the newer ones require a later
# version of chromium than is available on travis by default.
  - wget http://chromedriver.storage.googleapis.com/2.29/chromedriver_linux64.zip
  - unzip chromedriver_linux64.zip
  - export PATH=$PATH:$PWD
  - ./tool/travis-setup.sh

script:
  - ./tool/travis.sh
