name: webdriver
version: 0.10.0-pre.6
author: Google, Inc.
description: >
  Provides WebDriver bindings for Dart. These use the WebDriver JSON interface,
  and as such, require the use of the WebDriver remote server.
homepage: https://github.com/google/webdriver.dart
environment:
  sdk: '>=1.9.0 <2.0.0'
dependencies:
  crypto: '^0.9.0'
  test: '^0.12.0-rc.1'
dev_dependencies:
  path: '^1.3.5'
