name: webdriver
version: 1.0.1
author: Marc Fisher II <fisherii@google.com>
description: >
  Provides WebDriver bindings for Dart. These use the WebDriver JSON interface,
  and as such, require the use of the WebDriver remote server.
homepage: https://github.com/google/webdriver.dart
environment:
  sdk: '>=1.10.0 <2.0.0'
dependencies:
  matcher: '^0.12.0+1'
  path: '^1.3.6'
  stack_trace: '^1.3.4'
  unittest: '^0.11.6+1'
dev_dependencies:
  test: '^0.12.3+8'

